services:
  kong:
    image: kong:3.7
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    ports:
      - "8004:8000" # Kong proxy port
      - "8443:8443" # Kong proxy SSL port
      - "8001:8001" # Kong admin API port
      - "8444:8444" # Kong admin API SSL port
    volumes:
      - ./kong:/etc/kong/
    extra_hosts:
      - host.docker.internal:host-gateway

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
      RABBITMQ_PORT: 5672
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_VHOST: vhost
    ports:
      - 5672:5672
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  auth-api-database:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_SCHEMA}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "54321:5432"
    volumes:
      - auth-api-database-data:/var/lib/postgresql/data

  auth-api:
    #build:
    #context: ../../auth-api/
    #dockerfile: Dockerfile
    image: nahtann/loomi-bank-auth-api:latest
    ports:
      - "4001:4001"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      NODE_ENV: production
      PORT: 4001
      APP_URL: ${APP_URL}
      DATABASE_HOST: auth-api-database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@auth-api-database:5432/${DATABASE_SCHEMA}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}

volumes:
  rabbitmq-data:
  auth-api-database-data:
