services:
  database:
    container_name: bank-api-database
    image: "postgres:latest"
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_SCHEMA}
