export const AppEvents = Object.freeze({
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",

  BANKING_DETAILS_CREATED: "BANKING_DETAILS_CREATED",
  BAKING_DETAILS_UPDATED: "BAKING_DETAILS_UPDATED",
});
